services:
  db:
    image: postgres
    container_name: clonerdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cloner
      - POSTGRES_USER=blackroom
      - POSTGRES_PASSWORD=a.b.33!?
    volumes:
      - cloner-postgres-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_cloner
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: inside.black.room@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 'a.b.33!?'
    ports:
      - "5050:80"
volumes:
  cloner-postgres-data:
